server:
  port: 8081

spring:
  application:
    name: identity-service

  datasource:
    # QUAN TRỌNG: Đổi localhost thành tên service postgres của bạn (ví dụ: postgres-identity)
    url: jdbc:postgresql://postgres-identity:5432/identity_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    # Ép buộc tạo lại bảng mỗi khi khởi động
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        # Đảm bảo dùng đúng Dialect cho Postgres 10 trở lên
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: DayLaMotDoanBaoMatRatDaiChoHeThongHomeVerseCuaBan2026DeDungChoThuatToanHS256
  expiration: 86400000

homeverse:
  services:
    customer: http://customer-service:8082

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE