server:
  port: 8082

spring:
  application:
    name: customer-service
  datasource:
    # LỖI TẠI ĐÂY: Trong Docker không dùng 'localhost'
    # Phải dùng tên service của Postgres trong docker-compose.yml (ví dụ: postgres-customer)
    url: jdbc:postgresql://postgres-customer:5432/customer_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # Ép tạo lại bảng mỗi khi khởi động
    show-sql: true
    # THÊM DÒNG NÀY ĐỂ HIBERNATE BIẾT CÁCH NÓI CHUYỆN VỚI POSTGRES
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: DayLaMotDoanBaoMatRatDaiChoHeThongHomeVerseCuaBan2026DeDungChoThuatToanHS256