server:
  port: 8086

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.homeverse.*,com.smartrental.*"

  datasource:
    # Lấy từ file .env, nếu trống sẽ dùng giá trị mặc định sau dấu hai chấm
    url: jdbc:postgresql://${PAYMENT_DB_HOST:postgres-payment}:5432/payment_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

# Cấu hình VNPAY - Khớp với tên biến trong file .env của Ân
vnpay:
  tmn-code: ${VNP_TMNCODE}
  hash-secret: ${VNP_HASHSECRET}
  pay-url: ${VNP_PAYURL}
  return-url: ${VNP_RETURNURL}

jwt:
  secret: ${JWT_SECRET}