events {}
http {
    server {
        listen 80;

        # Chuyển hướng các request Auth sang Identity Service
        location /auth/ {
            proxy_pass http://identity-service:8081/auth/;
        }

        # Chuyển hướng các request Admin sang Identity Service
        location /admin/ {
            proxy_pass http://identity-service:8081/admin/;
        }

        # Chuyển hướng các request Profile/KYC sang Customer Service
        location /customers/ {
            proxy_pass http://customer-service:8082/customers/;
        }
    }
}